#!/bin/bash

user=${USER:-"gitea"}
uid=${SUEXEC_UID:-"1000"}
gid=${SUEXEC_GID:-"1000"}

id -u ${user}

if [ 0 -ne $? ]; then
   # user not exists, create user
   adduser -S -H -D -h /data/git -s /bin/bash -u ${uid} -g ${gid} ${user}
else
   # user exist, make sure uid is correct
   uid=$(id -u ${user})
   export SUEXEC_UID=${uid}
   export SUEXEC_GID=${gid}
fi

passwd -d ${user}

if [ ! -d /data/git/.ssh ]; then
    mkdir -p /data/git/.ssh
    chmod 700 /data/git/.ssh
fi

if [ ! -f /data/git/.ssh/environment ]; then
    echo "GITEA_CUSTOM=/data/gitea" >| /data/git/.ssh/environment
    chmod 600 /data/git/.ssh/environment
fi

if [ ! -f /data/gitea/conf/app.ini ]; then
    mkdir -p /data/gitea/conf
    cp /etc/gitea/app.ini /data/gitea/conf/app.ini

    # Set INSTALL_LOCK to true only if SECRET_KEY is not empty and
    # INSTALL_LOCK is empty
    #if [ -n "$SECRET_KEY" ] && [ -z "$INSTALL_LOCK" ]; then
    #    INSTALL_LOCK=true
    #fi

fi

chown -R ${uid}:${gid} /data
chmod 0755 /data/gitea /data/git
export GITEA_CUSTOM=/data/gitea
